# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-security-hub
  description: Terraform module to provision AWS Security Hub
  homepage: https://cloudposse.com/accelerate
  topics: compliance, terraform, terraform-modules



